export const employerJobs = [
  {
    id: 'product-designer',
    title: 'Senior Product Designer',
    team: 'Design',
    location: 'New York, NY',
    type: 'Full-time',
    mode: 'Remote',
    salary: '$150k - $190k',
    status: 'Open',
    applicants: 84,
    shortlisted: 12,
    score: 92,
    posted: 'Aug 12, 2026',
    expires: 'Sep 12, 2026',
    views: 1240,
    conversion: '6.8%',
    priority: 'High',
    requirements: ['Design systems', 'Enterprise SaaS', 'User research'],
    description: 'Lead product design for customer-facing experiences across web and mobile.',
  },
  {
    id: 'frontend-engineer',
    title: 'Frontend Engineer',
    team: 'Engineering',
    location: 'Austin, TX',
    type: 'Full-time',
    mode: 'Hybrid',
    salary: '$135k - $170k',
    status: 'Open',
    applicants: 67,
    shortlisted: 9,
    score: 88,
    posted: 'Aug 10, 2026',
    expires: 'Sep 10, 2026',
    views: 980,
    conversion: '6.1%',
    priority: 'High',
    requirements: ['React', 'TypeScript', 'Accessibility'],
    description: 'Build polished React interfaces and improve dashboard performance.',
  },
  {
    id: 'growth-marketer',
    title: 'Growth Marketing Lead',
    team: 'Marketing',
    location: 'Remote',
    type: 'Contract',
    mode: 'Remote',
    salary: '$95k - $130k',
    status: 'Draft',
    applicants: 31,
    shortlisted: 5,
    score: 74,
    posted: 'Aug 8, 2026',
    expires: 'Sep 8, 2026',
    views: 540,
    conversion: '5.7%',
    priority: 'Medium',
    requirements: ['Lifecycle marketing', 'Analytics', 'Paid acquisition'],
    description: 'Own acquisition campaigns, lifecycle experiments, and reporting.',
  },
];

export const applicants = [
  {
    id: 'sarah-johnson',
    name: 'Sarah Johnson',
    role: 'Senior Product Designer',
    company: 'Google',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=160&q=80',
    location: 'New York, NY',
    experience: '6 years',
    score: 94,
    stage: 'Interview',
    applied: '2h ago',
    skills: ['Figma', 'UX Research', 'Design Systems'],
    source: 'Recommended match',
    availability: '2 weeks',
    cvFile: 'Sarah_Johnson_Product_Designer_CV.pdf',
    cvUpdated: 'Updated Aug 14, 2026',
    cvSummary: 'Portfolio-led CV with SaaS case studies, design systems ownership, and research highlights.',
    note: 'Strong product systems background with enterprise SaaS work.',
  },
  {
    id: 'michael-chen',
    name: 'Michael Chen',
    role: 'Frontend Engineer',
    company: 'Microsoft',
    location: 'Austin, TX',
    experience: '5 years',
    score: 89,
    stage: 'Shortlisted',
    applied: '6h ago',
    skills: ['React', 'TypeScript', 'Performance'],
    source: 'Applied directly',
    availability: 'Immediate',
    cvFile: 'Michael_Chen_Frontend_Engineer_CV.pdf',
    cvUpdated: 'Updated Aug 13, 2026',
    cvSummary: 'Engineering CV focused on React architecture, TypeScript, performance, and accessibility.',
    note: 'Great dashboard portfolio and clean component architecture.',
  },
  {
    id: 'amina-bello',
    name: 'Amina Bello',
    role: 'Growth Marketing Lead',
    company: 'Spotify',
    avatarUrl: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=160&q=80',
    location: 'Lagos, NG',
    experience: '7 years',
    score: 86,
    stage: 'Review',
    applied: '1d ago',
    skills: ['Lifecycle', 'Analytics', 'Paid Social'],
    source: 'Talent pool',
    availability: '30 days',
    cvFile: 'Amina_Bello_Growth_Marketing_CV.pdf',
    cvUpdated: 'Updated Aug 11, 2026',
    cvSummary: 'Campaign and lifecycle marketing CV with acquisition metrics and analytics depth.',
    note: 'Strong experimentation history and clear revenue impact.',
  },
  {
    id: 'daniel-ross',
    name: 'Daniel Ross',
    role: 'Senior Product Designer',
    company: 'Figma',
    location: 'Remote',
    experience: '4 years',
    score: 81,
    stage: 'Review',
    applied: '2d ago',
    skills: ['Prototyping', 'Interaction', 'Workshops'],
    source: 'Referral',
    availability: '3 weeks',
    cvFile: 'Daniel_Ross_Product_Designer_CV.pdf',
    cvUpdated: 'Updated Aug 9, 2026',
    cvSummary: 'Craft-focused CV covering prototypes, interaction design, workshops, and product discovery.',
    note: 'Excellent craft, needs deeper systems leadership review.',
  },
  {
    id: 'priya-nair',
    name: 'Priya Nair',
    role: 'Frontend Engineer',
    company: 'Amazon',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=160&q=80',
    location: 'Seattle, WA',
    experience: '8 years',
    score: 78,
    stage: 'New',
    applied: '3d ago',
    skills: ['Accessibility', 'React', 'Testing'],
    source: 'Applied directly',
    availability: '45 days',
    cvFile: 'Priya_Nair_Frontend_Engineer_CV.pdf',
    cvUpdated: 'Updated Aug 7, 2026',
    cvSummary: 'Senior frontend CV with testing strategy, accessibility leadership, and platform delivery.',
    note: 'Senior delivery background with strong accessibility instincts.',
  },
  {
    id: 'james-wilson',
    name: 'James Wilson',
    role: 'Product Manager',
    company: 'Nova Cloud',
    location: 'Boston, MA',
    experience: '6 years',
    score: 84,
    stage: 'New',
    applied: '4d ago',
    skills: ['Product Strategy', 'Roadmaps', 'Agile'],
    source: 'Recommended match',
    availability: '2 weeks',
    cvFile: 'James_Wilson_Product_Manager_CV.pdf',
    cvUpdated: 'Updated Aug 6, 2026',
    cvSummary: 'Product management CV covering platform strategy, roadmap planning, and agile delivery.',
    note: 'Strong cross-functional leadership and product planning experience.',
  },
  {
    id: 'olivia-martin',
    name: 'Olivia Martin',
    role: 'UX Researcher',
    company: 'Airbnb',
    location: 'Remote',
    experience: '5 years',
    score: 88,
    stage: 'Review',
    applied: '5d ago',
    skills: ['User Research', 'Interviews', 'Usability Testing'],
    source: 'Talent pool',
    availability: '30 days',
    cvFile: 'Olivia_Martin_UX_Researcher_CV.pdf',
    cvUpdated: 'Updated Aug 5, 2026',
    cvSummary: 'Research-focused CV with qualitative studies, usability testing, and insight synthesis.',
    note: 'Excellent research practice with clear evidence of product impact.',
  },
  {
    id: 'noah-kim',
    name: 'Noah Kim',
    role: 'Data Analyst',
    company: 'Stripe',
    location: 'Chicago, IL',
    experience: '3 years',
    score: 79,
    stage: 'New',
    applied: '6d ago',
    skills: ['SQL', 'Python', 'Dashboards'],
    source: 'Applied directly',
    availability: 'Immediate',
    cvFile: 'Noah_Kim_Data_Analyst_CV.pdf',
    cvUpdated: 'Updated Aug 4, 2026',
    cvSummary: 'Analytics CV focused on SQL, Python automation, reporting, and decision support.',
    note: 'Practical analytics background with strong reporting fundamentals.',
  },
  {
    id: 'emma-davis',
    name: 'Emma Davis',
    role: 'Content Strategist',
    company: 'Slack',
    location: 'San Francisco, CA',
    experience: '4 years',
    score: 83,
    stage: 'Shortlisted',
    applied: '1w ago',
    skills: ['Content Strategy', 'SEO', 'Editorial'],
    source: 'Referral',
    availability: '3 weeks',
    cvFile: 'Emma_Davis_Content_Strategist_CV.pdf',
    cvUpdated: 'Updated Aug 3, 2026',
    cvSummary: 'Content strategy CV covering editorial systems, SEO programs, and audience growth.',
    note: 'Clear writing portfolio and thoughtful content operations experience.',
  },
  {
    id: 'lucas-garcia',
    name: 'Lucas Garcia',
    role: 'DevOps Engineer',
    company: 'Microsoft',
    location: 'Denver, CO',
    experience: '7 years',
    score: 91,
    stage: 'Interview',
    applied: '1w ago',
    skills: ['AWS', 'Kubernetes', 'CI/CD'],
    source: 'Recommended match',
    availability: '45 days',
    cvFile: 'Lucas_Garcia_DevOps_Engineer_CV.pdf',
    cvUpdated: 'Updated Aug 2, 2026',
    cvSummary: 'Infrastructure CV featuring cloud operations, Kubernetes, delivery automation, and reliability.',
    note: 'High-confidence infrastructure candidate with strong systems ownership.',
  },
];
