import { useState } from 'react';
import { FaCheckCircle, FaCreditCard, FaLock, FaReceipt } from 'react-icons/fa';
import { usePayments } from '../../context/PaymentContext';

function PaymentsPage() {
  const { payments, confirmEmployerPayment, markJobCompleted } = usePayments();
  const [completionPaymentId, setCompletionPaymentId] = useState<string | null>(null);
  const employerPayments = payments.filter((payment) => payment.paymentType === 'One-time payment');
  const completionPayment = employerPayments.find((payment) => payment.id === completionPaymentId);
  return <div className="payment-page"><section className="payment-hero"><div><span>Employer payments</span><h1>Fund your work posts</h1><p>Pay securely, track held payments, and confirm completed work.</p></div><FaCreditCard /></section><section className="payment-panel"><div className="payment-heading"><div><span><FaLock /> Payment workflow</span><h2>Jobs and payment status</h2></div></div><div className="payment-list">{employerPayments.map((payment) => <article className="payment-row payment-row--stack" key={payment.id}><div><strong>{payment.jobTitle}</strong><p>{payment.employer} / Worker: {payment.seeker}</p></div><strong>${payment.amount.toLocaleString()}</strong><span className={`payment-status payment-status--${payment.status.toLowerCase().replaceAll(' ', '-')}`}>{payment.status}</span><div className="payment-actions">{payment.status === 'Awaiting payment' ? <button type="button" onClick={() => confirmEmployerPayment(payment.id)}><FaCreditCard /> Pay admin</button> : null}{payment.status === 'Paid to admin' ? <button type="button" onClick={() => setCompletionPaymentId(payment.id)}><FaCheckCircle /> Confirm job complete</button> : null}</div></article>)}</div></section><section className="payment-panel"><div className="payment-heading"><div><span><FaReceipt /> Protection</span><h2>How payment is released</h2></div></div><p className="payment-copy">Your payment is held by the platform until the work is completed. After you confirm delivery, admin credits the worker&apos;s balance.</p></section>{completionPayment ? <div className="payment-modal-backdrop" role="presentation"><div className="payment-modal" role="dialog" aria-modal="true" aria-labelledby="completion-modal-title"><h2 id="completion-modal-title">Confirm job completion</h2><p>Confirm that <strong>{completionPayment.jobTitle}</strong> for {completionPayment.seeker} has been completed successfully.</p><p className="payment-modal__amount">Held payment: ${completionPayment.amount.toLocaleString()}</p><div className="payment-actions"><button type="button" className="payment-button-secondary" onClick={() => setCompletionPaymentId(null)}>Cancel</button><button type="button" onClick={() => { markJobCompleted(completionPayment.id); setCompletionPaymentId(null); }}><FaCheckCircle /> Yes, confirm completion</button></div></div></div> : null}</div>;
}
export default PaymentsPage;
