import { FaCheckCircle, FaCoins, FaCreditCard, FaMoneyBillWave, FaTimesCircle } from 'react-icons/fa';
import { usePayments } from '../../context/PaymentContext';

function AdminPaymentsPage() {
  const { payments, withdrawals, confirmEmployerPayment, markJobCompleted, creditSeeker, updateWithdrawalStatus, platformFeePercent } = usePayments();
  const freelancePayments = payments.filter((payment) => payment.paymentType === 'One-time payment');
  const received = freelancePayments.filter((payment) => payment.status !== 'Awaiting payment').reduce((total, payment) => total + payment.amount, 0);
  const held = freelancePayments.filter((payment) => ['Paid to admin', 'Completed'].includes(payment.status)).reduce((total, payment) => total + payment.amount, 0);
  return <div className="payment-page"><section className="payment-hero"><div><span>Admin finance control</span><h1>Payment operations</h1><p>Only one-time freelance payments enter the admin-held payment workflow.</p></div><FaCoins /></section><section className="payment-stat-grid"><article><span>Received by admin</span><strong>${received.toLocaleString()}</strong><small>Freelance payments confirmed</small></article><article><span>Held in workflow</span><strong>${held.toLocaleString()}</strong><small>Waiting for completion or credit</small></article><article><span>Withdrawal requests</span><strong>{withdrawals.filter((withdrawal) => withdrawal.status === 'Pending').length}</strong><small>Need admin review</small></article><article><span>Admin fee</span><strong>{platformFeePercent}%</strong><small>Applied to withdrawals</small></article></section><section className="payment-panel"><div className="payment-heading"><div><span><FaCreditCard /> Employer funding</span><h2>Freelance payment ledger</h2></div></div><div className="payment-list">{freelancePayments.map((payment) => <article className="payment-row payment-row--stack" key={payment.id}><div><strong>{payment.jobTitle}</strong><p>{payment.employer} pays for {payment.seeker}</p></div><strong>${payment.amount.toLocaleString()}</strong><span className={`payment-status payment-status--${payment.status.toLowerCase().replaceAll(' ', '-')}`}>{payment.status}</span><div className="payment-actions">{payment.status === 'Awaiting payment' ? <button type="button" onClick={() => confirmEmployerPayment(payment.id)}>Confirm payment</button> : null}{payment.status === 'Paid to admin' ? <button type="button" onClick={() => markJobCompleted(payment.id)}>Mark completed</button> : null}{payment.status === 'Completed' ? <button type="button" onClick={() => creditSeeker(payment.id)}><FaCheckCircle /> Credit seeker</button> : null}</div></article>)}</div></section><section className="payment-panel"><div className="payment-heading"><div><span><FaMoneyBillWave /> Withdrawals</span><h2>Review seeker payouts</h2></div></div><div className="payment-list">{withdrawals.map((withdrawal) => <article className="payment-row" key={withdrawal.id}><div><strong>{withdrawal.seeker}</strong><p>{withdrawal.method} / requested {withdrawal.requestedAt}</p></div><strong>${withdrawal.payout.toLocaleString()}</strong><span className={`payment-status payment-status--${withdrawal.status.toLowerCase()}`}>{withdrawal.status}</span><div className="payment-actions"><button type="button" onClick={() => updateWithdrawalStatus(withdrawal.id, 'Paid')}><FaCheckCircle /> Mark paid</button><button type="button" onClick={() => updateWithdrawalStatus(withdrawal.id, 'Declined')}><FaTimesCircle /> Decline</button></div></article>)}</div></section></div>;
}
export default AdminPaymentsPage;
